wandb_version: 1

learning_rate:
  desc: null
  value: 0.01
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.0
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716049051
    t:
      1:
      - 1
      - 4
      - 5
      - 6
      - 7
      - 8
      - 15
      - 53
      - 55
      - 105
      2:
      - 1
      - 4
      - 5
      - 6
      - 7
      - 8
      - 15
      - 53
      - 55
      - 105
      3:
      - 2
      - 16
      - 23
      4: 3.10.14
      5: 0.17.0
      8:
      - 4
      - 5
      13: darwin-arm64
